In [43]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold, cross_val_score

Требуется предсказать возраст ракушки по физическим измерениям

In [5]:
# Загрузите данные
data = pd.read_csv('abalone.csv')

In [6]:
data.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [7]:
# Преобразуйте признак Sex в числовой
data['Sex'] = data['Sex'].map(lambda x: 1 if x == 'M' else (-1 if x == 'F' else 0))

In [8]:
data.head()

,Sex,Length,Diameter,Height,WholeWeight,ShuckedWeight,VisceraWeight,ShellWeight,Rings
0,1,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,-1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,1,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,0,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [18]:
# Разделите содержимое файла .csv на признаки и целевую переменную.
# В последнем столбце записана целевая переменная, в остальных - признаки

data_target = data.Rings.values # отрежем целевую переменную

# Отдельно отрежем данные
data_features = data.iloc[:, :-1]

y = data_target
X = data_features

In [60]:
cv = KFold(n_splits=5, shuffle=True, random_state=1)

In [66]:
# Обучите случайный лес с различным числом деревьев от 1 до 50

def test_accuracy(cv, X, y):
    for k in range(1, 51):
        rf = RandomForestRegressor(n_estimators=k, random_state=1)
        rf.fit(X, y)
        score = cross_val_score(rf, X, y, cv=cv, scoring="r2").mean()
        print('Num of trees = {};'.format(k), 'score = {}'.format(score))

test_accuracy(cv, X, y)

Num of trees = 1; score = 0.10213869487724367
Num of trees = 2; score = 0.33841675515802144
Num of trees = 3; score = 0.4035798494618691
Num of trees = 4; score = 0.44272239896668103
Num of trees = 5; score = 0.4640207660674969
Num of trees = 6; score = 0.4705816327587792
Num of trees = 7; score = 0.4758306163523006
Num of trees = 8; score = 0.4817418456255852
Num of trees = 9; score = 0.4883478130215681
Num of trees = 10; score = 0.49446412480247826
Num of trees = 11; score = 0.4933965550001963
Num of trees = 12; score = 0.4979658763976154
Num of trees = 13; score = 0.5021364605722853
Num of trees = 14; score = 0.5064286962257328
Num of trees = 15; score = 0.5083311970432101
Num of trees = 16; score = 0.5105131438322147
Num of trees = 17; score = 0.5138482947993028
Num of trees = 18; score = 0.5163275412739493
Num of trees = 19; score = 0.519034688136388
Num of trees = 20; score = 0.5186735928723822
Num of trees = 21; score = 0.5198354233542501
Num of trees = 22; score = 0.5201583536722211
Num of trees = 23; score = 0.5210172709366251
Num of trees = 24; score = 0.5224031825808091
Num of trees = 25; score = 0.5226174639676071
Num of trees = 26; score = 0.5238061581717052
Num of trees = 27; score = 0.5241223522188981
Num of trees = 28; score = 0.525053745123244
Num of trees = 29; score = 0.5259703756348931
Num of trees = 30; score = 0.5265378216675755
Num of trees = 31; score = 0.5270998544306023
Num of trees = 32; score = 0.5283894082092784
Num of trees = 33; score = 0.5296165561229277
Num of trees = 34; score = 0.5295639554438379
Num of trees = 35; score = 0.529517247440473
Num of trees = 36; score = 0.5295996267890184
Num of trees = 37; score = 0.52913141344746
Num of trees = 38; score = 0.5291602576334833
Num of trees = 39; score = 0.5292409810274339
Num of trees = 40; score = 0.529067015963163
Num of trees = 41; score = 0.5293420056911183
Num of trees = 42; score = 0.5295732065337546
Num of trees = 43; score = 0.5293754946648532
Num of trees = 44; score = 0.5291192337563251
Num of trees = 45; score = 0.5283754660277202
Num of trees = 46; score = 0.5285204275493458
Num of trees = 47; score = 0.5287049445791908
Num of trees = 48; score = 0.5296127515437734
Num of trees = 49; score = 0.5303944554434498
Num of trees = 50; score = 0.5305963435394535